name: cv_e_commerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # for loaction permission
  geolocator: ^13.0.1
  # for state management
  get: ^4.6.6
  # for http request
  http: ^1.2.2
  # for dateformat
  intl: ^0.19.0
  # for lottie format
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/animation/
  fonts:
    - family: BrandinkSans
      fonts:
        - asset: assets/fonts/BrandinkSans-Regular.otf
          weight: 500
          style: normal
        - asset: assets/fonts/BrandinkSans-Light.otf
          weight: 300
          style: normal
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
        - asset: assets/fonts/Nunito-Italic-VariableFont_wght.ttf
          style: italic